# Generated by Django 3.2.5 on 2022-06-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_urlinputform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLinputForm',
            new_name='URLinput',
        ),
    ]
