# Generated by Django 3.2.5 on 2022-06-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_rename_urlinputform_urlinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlinput',
            old_name='inputURL',
            new_name='inputURL_value',
        ),
    ]
