# Generated by Django 3.2.5 on 2022-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_rename_inputurl_urlinput_inputurl_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlinput',
            old_name='inputURL_value',
            new_name='Enter_URL',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
